// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmifiuugweailufqcpah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptaWZpdXVnd2VhaWx1ZnFjcGFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDA0NjAsImV4cCI6MjA2NTUxNjQ2MH0.snvBZNy5hST1e9jZj-B11VrqoT7mgiuEWLDMzybkui0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);